/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package workshopsem2.main;

import javax.swing.JOptionPane;
import java.sql.*;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import workshopsem2.Utils;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tole
 */
public class LaporanPendapatan extends javax.swing.JFrame {

    /**
     * Creates new form LaporanPendapatan
     */
    public LaporanPendapatan() {
        initComponents();
    }
    
    boolean val(){
        if (jDateChooser2.getDate().after(jDateChooser3.getDate())) {
            JOptionPane.showMessageDialog(this, "Val False");
            return false;
        }
        
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(jButton1)
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (val()) {
            String query = "SELECT * FROM header_transaction join customer on customer.id_customer = header_transaction.id_customer where transaction_datetime_header_transaction >= '"+ new java.sql.Date(jDateChooser2.getDate().getTime()) +"' and transaction_datetime_header_transaction <= '"+ new java.sql.Date(jDateChooser3.getDate().getTime()) +"' order by transaction_datetime_header_transaction desc" ;
            DefaultTableModel tbl = new DefaultTableModel();
            tbl.addColumn("#");
            tbl.addColumn("Nama");
            tbl.addColumn("Tanggal Mulai");
            tbl.addColumn("Tanggal Berakhir");
            tbl.addColumn("Total");
            jTable1.setModel(tbl);
            try{
                int totalKeseluruhan = 0;
                Statement st = (Statement) Utils.getConnection().createStatement();
                ResultSet rs = st.executeQuery(query);
                List<Integer> idTransaction = new ArrayList<Integer>();
                List<String> namaCustomer = new ArrayList<String>();
                List<String> dateMulai = new ArrayList<String>();
                List<String> dateAkhir = new ArrayList<String>();
                while(rs.next()){
                    int id = rs.getInt("id_header_transaction");
                    idTransaction.add(id);
                    namaCustomer.add(rs.getString("nama_customer"));
                    dateMulai.add(rs.getDate("transaction_datetime_header_transaction").toString());
                    dateAkhir.add((rs.getDate("completion_datetime_header_transcation") != null) ? rs.getDate("completion_datetime_header_transcation").toString() : null);
                }
                for(int i = 0; i < idTransaction.size(); i++){
                    String queryGetTotal = "SELECT SUM(price_detail_transaction) as total from detail_transaction where id_header_transaction = " + idTransaction.get(i);
                    ResultSet rsTotal = st.executeQuery(queryGetTotal);
                    int total = 0;
                    if (rsTotal.next()) {
                        total = rsTotal.getInt("total");
                    } else {
                        total = 0;
                    }

                    totalKeseluruhan += total;
                    tbl.addRow(new Object[]{
                       i+1,
                       namaCustomer.get(i),
                       new SimpleDateFormat("dd MMMM YYYY").format(Date.valueOf(dateMulai.get(i))),
                       (dateAkhir.get(i) != null) ? new SimpleDateFormat("dd MMMM YYYY").format(Date.valueOf(dateAkhir.get(i))) : "-",
                       NumberFormat.getInstance(new Locale("in", "ID")).format(total)
                    });
                    jTable1.setModel(tbl);
                }
                jLabel1.setText("Total = Rp. " + String.valueOf(NumberFormat.getInstance(new Locale("in", "ID")).format(totalKeseluruhan)));
            } catch(Exception e){
                System.out.println(""+e);
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaporanPendapatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaporanPendapatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaporanPendapatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaporanPendapatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaporanPendapatan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
